upstream ui_server {
    server web:5000 fail_timeout=0;
}
upstream api_server {
    server web-api:5000 fail_timeout=0;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    charset utf-8;
    keepalive_timeout 5;

    add_header X-Request-ID $request_id;

    proxy_request_buffering off;
    proxy_http_version 1.1;

    # UI server
    location / {
        uwsgi_pass ui_server;
        include uwsgi_params;
        uwsgi_buffering off;
        uwsgi_request_buffering off;
        chunked_transfer_encoding off;
        uwsgi_param Host $host;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $forwarded_proto;
        uwsgi_param X-Request-ID $request_id;
        uwsgi_hide_header X-Session-ID;
        uwsgi_hide_header X-User-ID;
        client_max_body_size 100m;
    }

    # API
    location /api {
        uwsgi_pass api_server;
        include uwsgi_params;
        uwsgi_buffering off;
        uwsgi_request_buffering off;
        chunked_transfer_encoding off;
        uwsgi_param Host $host;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $forwarded_proto;
        uwsgi_param X-Request-ID $request_id;
        uwsgi_hide_header X-Session-ID;
        uwsgi_hide_header X-User-ID;
        client_max_body_size 100m;
    }

    # Large file uploads for records
    location ~ /api/records/.+/draft/files/.+/content(/[0-9]+)?/?$ {
        gzip off;
        uwsgi_pass api_server;
        include uwsgi_params;
        uwsgi_buffering off;
        uwsgi_request_buffering off;
        chunked_transfer_encoding off;
        uwsgi_param Host $host;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $forwarded_proto;
        uwsgi_param X-Request-ID $request_id;
        uwsgi_hide_header X-Session-ID;
        uwsgi_hide_header X-User-ID;
        client_max_body_size 50G;
    }

    # Static files served directly by nginx
    location /static {
        alias /opt/invenio/var/instance/static;
        autoindex off;
    }
}
